# Generated by Django 5.0.6 on 2024-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço')),
                ('imagem', models.ImageField(upload_to='', verbose_name='imagens/')),
                ('manual', models.FileField(upload_to='', verbose_name='pdfs/')),
            ],
        ),
    ]
