# Generated by Django 5.0.7 on 2024-07-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('posicao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hacker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('formacao', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('servico', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.clientes')),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.hacker')),
            ],
        ),
    ]
