# Generated by Django 5.0.7 on 2024-07-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='quantidade',
        ),
    ]
