# Generated by Django 5.0.7 on 2024-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_remove_clientes_posicao_remove_hacker_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='nome',
        ),
    ]
