# Generated by Django 5.0.6 on 2024-06-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROVA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pagina1',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='pagina3',
            new_name='Compras',
        ),
        migrations.RenameModel(
            old_name='pagina2',
            new_name='Usuarios',
        ),
        migrations.DeleteModel(
            name='PGinicial',
        ),
    ]
