# Generated by Django 5.0.6 on 2024-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROVA', '0002_rename_pagina1_clientes_rename_pagina3_compras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Ferminino', 'Ferminino')], max_length=15),
        ),
    ]
