# Generated by Django 5.0.6 on 2024-07-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jogos',
            new_name='jogo',
        ),
    ]
