# Generated by Django 5.1 on 2024-08-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materia', models.CharField(max_length=30)),
                ('selecao', models.ImageField(upload_to='foto_capa')),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especializacao', models.CharField(max_length=30)),
                ('selecao', models.ImageField(upload_to='foto_capa')),
            ],
        ),
    ]
