# Generated by Django 5.0.6 on 2024-06-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='famoso',
            name='foto',
            field=models.ImageField(default=0.0, upload_to='foto_perfil/'),
            preserve_default=False,
        ),
    ]
